 Q1. Total revenue generated by male vs. female customers
-- ------------------------------------------------------------
SELECT
    Gender,
    SUM(Purchase_Amount) AS Total_Revenue
FROM customers
GROUP BY Gender;

 Q2. Customers who used a discount but still spent more
--     than the average purchase amount
-- ------------------------------------------------------------
SELECT
    Customer_id,
    Purchase_Amount,
    Discount_Applied
FROM customers
WHERE Discount_Applied = 'Yes'
  AND Purchase_Amount > (
        SELECT AVG(Purchase_Amount) FROM customers
      )
ORDER BY Purchase_Amount DESC;
 
 
  Q3. Top 5 products with the highest average review rating
-- ------------------------------------------------------------
SELECT
    Item_Purchased,
    ROUND(AVG(Review_Rating), 2) AS Avg_Rating
FROM customers
GROUP BY Item_Purchased
ORDER BY Avg_Rating DESC
LIMIT 5;

Q4. Compare average Purchase Amount: Standard vs Express Shipping
-- ------------------------------------------------------------
SELECT
    Shipping_Type,
    ROUND(AVG(Purchase_Amount), 2) AS Avg_Purchase_Amount,
    COUNT(*) AS Num_Orders
FROM customers
WHERE Shipping_Type IN ('Standard', 'Express')
GROUP BY Shipping_Type;

Q5. Do subscribed customers spend more? Avg spend & total
--     revenue: subscribers vs non-subscribers
-- ------------------------------------------------------------
SELECT
    Subscription_Status,
    ROUND(AVG(Purchase_Amount), 2) AS Avg_Spend,
    SUM(Purchase_Amount) AS Total_Revenue,
    COUNT(*) AS Num_Customers
FROM customers
GROUP BY Subscription_Status;

Q6. Top 5 products with the highest % of purchases made
--     with a discount applied
-- ------------------------------------------------------------
SELECT
    Item_Purchased,
    ROUND(
        SUM(CASE WHEN Discount_Applied = 'Yes' THEN 1 ELSE 0 END) * 100.0
        / COUNT(*), 2
    ) AS Discount_rate
FROM customers
GROUP BY Item_Purchased
ORDER BY Discount_rate DESC
LIMIT 5;
 
 
  Q7. Segment customers into New / Returning / Loyal based on
--     Previous Purchases, and count each segment
--     (Assumption: New = 0-2, Returning = 3-10, Loyal = 11+
--      -> adjust thresholds to match your business definition)
-- ------------------------------------------------------------
SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count
FROM (
    SELECT
        customer_id,
        CASE
            WHEN Previous_Purchases <= 2 THEN 'New'
            WHEN Previous_Purchases BETWEEN 3 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_Segment
    FROM customers
) AS segmented
GROUP BY Customer_Segment
ORDER BY Customer_Count DESC;
 
 
 Q8. Top 3 most purchased products within each category
-- ------------------------------------------------------------
SELECT
    Category,
    Item_Purchased,
    Purchase_Count
FROM (
    SELECT
        Category,
        Item_Purchased,
        COUNT(*) AS Purchase_Count,
        RANK() OVER (PARTITION BY Category ORDER BY COUNT(*) DESC) AS rnk
    FROM customers
    GROUP BY Category, Item_Purchased
) AS ranked

Q9. Are repeat buyers (>5 previous purchases) more likely
--     to subscribe? Subscription rate by buyer type
-- ------------------------------------------------------------
SELECT
    Buyer_Type,
    Subscription_Status,
    COUNT(*) AS Customer_Count,
    ROUND(
        COUNT(*) * 100.0 / SUM(COUNT(*)) OVER (PARTITION BY Buyer_Type), 2
    ) AS Pct_Within_Buyer_Type
FROM (
    SELECT
        Customer_id,
        Subscription_Status,
        CASE WHEN Previous_Purchases > 5 THEN 'Repeat Buyer'
             ELSE 'Non-Repeat Buyer'
        END AS Buyer_Type
    FROM customers
) AS tagged
GROUP BY Buyer_Type, Subscription_Status
ORDER BY Buyer_Type, Subscription_Status;
 
 WHERE rnk <= 3
ORDER BY Category, Purchase_Count DESC;


  Q10. Revenue contribution of each age group
 - ------------------------------------------------------------
SELECT
    Age_Group,
    SUM(Purchase_Amount) AS Total_Revenue,
    ROUND(
        SUM(Purchase_Amount) * 100.0
        / (SELECT SUM(Purchase_Amount) FROM customers), 2
    ) AS Revenue_Pct
FROM customers
GROUP BY Age_Group
ORDER BY Total_Revenue DESC;
 
 